name: linux_interactor
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  ffigen: ^9.0.1

dependencies:
  ffi: ^2.1.0
  test: ^1.22.0

ffigen:
  name: "InteractorBindings"
  description: "Bindings for Interactor"
  output: "lib/interactor/bindings.dart"
  compiler-opts:
    - "-I../native/small/third_party"
  headers:
    entry-points:
      - "../native/interactor.h"
      - "../native/interactor_dart.h"
      - "../native/interactor_constants.h"
  globals:
    exclude:
      - "_(.*)"
      - "ck(.*)"
  functions:
    leaf:
      include:
        - "interactor_dart_.*"
    symbol-address:
      include:
        - ".*"
    exclude:
      - "_(.*)"
      - "ck(.*)"
      - "io_uring(.*)"
  macros:
    exclude:
      - "_(.*)"
      - "true"
      - "false"
      - "CK(.*)"
  typedefs:
    exclude:
      - "_(.*)"
  structs:
    exclude:
      - "_(.*)"
      - "max_align_t"
      - "file_(.*)"
      - "io_uring_probe"
