name: linux_interactor
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  ffigen: ^9.0.1

dependencies:
  ffi: ^2.1.0
  test: ^1.22.0

ffigen:
  name: "InteractorBindings"
  description: "Bindings for Interactor"
  output: "lib/interactor/bindings.dart"
  compiler-opts:
    - "-I../native/include"
    - "-I../dependencies/small/include"
    - "-I../dependencies/small/include/small"
    - "-I../dependencies/small/third_party"
    - "-I../_deps/small-build/small/include"
    - "-I../build/_deps/small-build/small/include"
  headers:
    entry-points:
      - "../native/include/interactor_native.h"
      - "../native/interactor_dart.h"
      - "../native/interactor_constants.h"
      - "../native/test.h"
  globals:
    exclude:
      - "_(.*)"
  functions:
    leaf:
      include:
        - "interactor_dart_.*"
    symbol-address:
      include:
        - ".*"
    exclude:
      - "_(.*)"
      - "io_uring(.*)"
      - "interactor_memory(.*)"
      - "interactor_pool(.*)"
      - "interactor_allocator(.*)"
      - "interactor_messages_pool(.*)"
      - "interactor_buffers_pool(.*)"
      - "interactor_data_pool(.*)"
      - "interactor_native(.*)"
      - "interactor_payload_pool(.*)"
      - "slab_(.*)"
  macros:
    exclude:
      - "_(.*)"
      - "true"
      - "false"
  typedefs:
    exclude:
      - "_(.*)"
  structs:
    exclude:
      - "_(.*)"
      - "max_align_t"
      - "file_(.*)"
      - "io_uring_probe"
