name: linux_interactor
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  ffigen: ^7.2.5

dependencies:
  ffi: ^2.0.1
  retry: ^3.1.1
  test: ^1.22.0

ffigen:
  name: "InteractorBindings"
  description: "Bindings for Interactor"
  output: "lib/interactor/bindings.dart"
  headers:
    entry-points:
      - "../native/interactor.h"
  globals:
    exclude:
      - "_(.*)"
      - "ck(.*)"
  functions:
    symbol-address:
      include:
        - ".*"
    exclude:
      - "_(.*)"
      - "ck(.*)"
      - "io_uring(.*)"
  macros:
    exclude:
      - "_(.*)"
      - "true"
      - "false"
      - "CK(.*)"
  typedefs:
    exclude:
      - "_(.*)"
  structs:
    exclude:
      - "_(.*)"
      - "max_align_t"
      - "file_(.*)"
      - "io_uring_probe"