// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for Interactor
class InteractorBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  InteractorBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  InteractorBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void interactor_initialize() {
    return _interactor_initialize();
  }

  late final _interactor_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('interactor_initialize');
  late final _interactor_initialize =
      _interactor_initializePtr.asFunction<void Function()>();

  late final addresses = _SymbolAddresses(this);
}

class _SymbolAddresses {
  final InteractorBindings _library;
  _SymbolAddresses(this._library);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>
      get interactor_initialize => _library._interactor_initializePtr;
}
